{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "autoquoter-bot.fullname" . }}
  labels:
    {{- include "autoquoter-bot.labels" . | nindent 4 }}
type: Opaque
stringData:
  config.json: {{ .Values.config | toJson | quote }}
{{- end }}
